/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.app

import com.example.app.di.mainModule
import org.koin.test.check.checkModules
import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun `test koin dependency graph`() {
        checkModules {
            modules(mainModule)
        }
    }
}
